name: Test

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20 
      id: go

    - name: Get dependencies
      working-directory: ./
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      working-directory: ./
      run: go test -v .