package validations

import (
	"fmt"
	"strings"
)

// ValidateSHA512256 validates that a given value is a valid SHA512-256 hash.
// It takes an interface{} value and returns the validated hash as a string,
// the hash generated by the GenerateSHA3256 function, and an error if any.
func ValidateSHA512256(value interface{}) (string, string, error) {
	v, ok := value.(string)
	if !ok {
		return "", "", fmt.Errorf("value is not string: %v", value)
	}
	v = strings.ToLower(v)
	e := ValidateRegEx(`^[0-9a-f]{64}$`, v)
	if e != nil {
		return "", "", e
	}

	return v, GenerateSHA3256(v), nil
}
